<?php 
session_start(); 
require("config.php");

if(!isset($_SESSION["phase"])) { session_unset(); ?><!DOCTYPE html>
<html lang="en">
<head>
<title>Who are We? - The Game - Phase 7</title>
<link rel="stylesheet" href="style.css">
</head>
<body>
<h1><a href="https://whoarewe.games/" title="Who are We?"><em>Who are We?</em> - The Game</a></h1> 
<h2>Phase 7</h2>
<p>A security alert was raised.</p>
<p>Unfortunately, this is the end of your game, if any was in progress.</p>
</body>
</html> 
<?php die(); }
if(isset($_SESSION["phase"]) && $_SESSION["phase"] >= 7 ) { session_unset();  ?><!DOCTYPE html>
<html lang="en">
<head>
<title>Who are We? - The Game - Phase 7</title>
<link rel="stylesheet" href="style.css">
</head>
<body>
<h1><a href="https://whoarewe.games/" title="Who are We?"><em>Who are We?</em> - The Game</a></h1> 
<h2>Phase 7</h2>
<p>A security alert was raised.</p>
<p>Unfortunately, this is the end of your game, if any was in progress.</p>
</body>
</html> 
<?php die(); } 
if($_POST["nonce"] != $_SESSION["nonce"] ) { session_unset();  ?><!DOCTYPE html>
<html lang="en">
<head>
<title>Who are We? - The Game - Phase 7</title>
<link rel="stylesheet" href="style.css">
</head>
<body>
<h1><a href="https://whoarewe.games/" title="Who are We?"><em>Who are We?</em> - The Game</a></h1> 
<h2>Phase 7</h2>
<p>A security alert was raised.</p>
<p>Unfortunately, this is the end of your game, if any was in progress.</p>
</body>
</html> 
<?php die(); } 

$_SESSION["phase"] = 7; 
$_SESSION["nonce"] = bin2hex(random_bytes(32));

$conn = new mysqli($dbhost, $dbuser, $dbpass, $dbname);

if ($conn->connect_error) { header("Location: https://whoarewe.games/omg.php"); die(); }

foreach($_POST as $key => $value) {

	if($key == "nonce") continue;

	$stmt = $conn->prepare("INSERT INTO labels(surveyor, aspect, cluster, label) values (?, ?, ?, ?)");

	if (!$stmt) { $conn->close(); header("Location: https://whoarewe.games/omg.php"); die(); }

	$stmt->bind_param("isii", $surveyor, $aspect, $cluster, $label);
	$surveyor = $_SESSION["player"];
	$aspect = preg_replace('/[0-9]+/', '', $key);
	$cluster = preg_replace('/[^0-9]/', '', $key );
	$label = $value;
	if($stmt->execute()) {
		$stmt->close();
	}
	else { $stmt->close(); $conn->close(); header("Location: https://whoarewe.games/omg.php"); die(); }
}

$conn->close();

?>
<!DOCTYPE html>
<html lang="en">
<head>
<title>Who are We? - The Game - Phase 7</title>
<link rel="stylesheet" href="style.css">
<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.6.4/jquery.min.js"></script>
<script>setInterval(function(){$.ajax({url: "alive.php"}).done(function( response ) {console.log(response);});},60000); </script>
</head>
<body>
<h1><a href="https://whoarewe.games/" title="Who are We?"><em>Who are We?</em> - The Game</a></h1> 
<h2>Phase 7</h2>
<p>Thank you for your hard work.</p>
<p>Now a little bit of suspence, waiting for each of the other participants to complete the manual labelling of the groups generated by their survey, and for the system to generate the final rankings.</p>

<p id="progress"></p>
<script>
var checkProgress = function() {
	$.ajax({url: "labelling_progress.php"})
	.done(function( progressString ) {
		try {
			var progress = JSON.parse(progressString);
			if(progress.generated == progress.total) {
				window.location.replace("https://whoarewe.games/phase8.php?nonce=<?=$_SESSION["nonce"]?>");
			}
			else {
				$("#progress").html("At "+(new Date()).toLocaleTimeString()+" the <strong>" + Math.round(progress.generated/progress.total*100) + "%</strong> of the labelling had been completed.");
			}
		}
		catch(e) {
			clearInterval(interval);
			if(progressString == "fault") location.replace("https://whoarewe.games/omg.php"); else $("html").html(progressString);
		}
	})
	.fail(function(data, textStatus, xhr) {
		clearInterval(interval);
		location.replace("https://whoarewe.games/omg.php");
	});
};

var interval = setInterval(checkProgress, 10000);

checkProgress();

</script>
</body>
</html>